spring:
  application:
    name: socialnetworkbackend

  mail:
    host: smtp.gmail.com
    port: 587
    username: socialnetworkmb7@gmail.com
    password: byqpvbpfcbhcdxkz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8081
  servlet:
    session:
      cookie:
        same-site: strict

logging:
  file:
    name: app.log

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: 86_400_000
